### ISSUE TITLE
Incorrect route selection near Sint-Jozef-Londerzeel

### ISSUE THREAD

**Issue by marcgemis** [vmarc/knooppuntnet#128] opened 2021-01-04 19:43 UTC
Whenever I select this particular route near Sint-Jozef-Londerzeel, too many ways are selected. I have not seen this behaviour for other routes. I checked the route in OSM, but it seems correct.

- select node 312 at the east end of Heetgatstraetje, a bit south of Sint-Jozef-Londerzeel
- select the route between 312 and 38 (you cannot select 38 directly, otherwise the route goes via 311).
- the result is that a loop from 312, over 38 and 311 back to 312 gets selected.

**Comment by vmarc** [comment] 2021-01-04 21:18
@marcgemis thanks for reporting this problem!

It seems there is already something wrong with selecting the startnode. It should be shown immediately under the "Compact" header in the sidebar. Under the "Detail" header, only an empty circle is shown. This is not ok. I will further investigate.

**Comment by marcgemis** [comment] 2021-01-05 04:46
The startnode never appears in the list. No matter where you start.

**Comment by vmarc** [comment] 2021-01-05 21:02
The problem with the start node name is caused by the changes for issue #102 (and is fixed in the mean while). But this issue was unrelated to the problem with the wrong route selection.  

The route between 312 and 38 contains 2 ways with tag oneway=yes: [Topmolen](https://www.openstreetmap.org/way/638659971) and [Breendonkstraat](https://www.openstreetmap.org/way/12965774).  These tags had an unwanted effect on the route selection. This has been fixed. Now it is possible to plan a route via 312-38:

![xx](https://user-images.githubusercontent.com/6596480/103697892-da413400-4fa0-11eb-9574-4fa68222cf2c.png)

**Closed** 2021-01-05 21:03 UTC
Labels: bug
