### ISSUE TITLE
[Analysis] Circular route with an intermediate *-node gives "facts". 

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#126] opened 2020-11-30 11:51 UTC
https://knooppuntnet.nl/nl/analysis/route/11858847 is a route from node 75 to node 75, passing a *-node on the way.
This gives the "facts" redundant node, unexpected name and sorting error. To me, none of these facts are true: in JOSM the first node of the first way is 75, the continuity line shows a closed loop so the sorting is ok, and the last node of the last way is also 75.  
The intermediate *-node should be allowed (that's implemented, isn't it?). Maybe the special closed-loop logic does't know about the *-nodes yet?
Note: there are now several cases with multiple *-nodes in one route, so this could also happen in circular routes. Murphy says if it can happen, it will.

**Comment by vmarc** [comment] 2021-07-22 16:54
The situation of route [75-75](https://knooppuntnet.nl/nl/analysis/route/11858847) (today no longer active) has been reproduced in case study [Issue126_CircularRoute](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/test/scala/kpn/server/analyzer/engine/analysis/caseStudies/Issue126_CircularRoute.scala) with the situation on "2020-11-30 00:00:00".

The problem is resolved in the analyzer which is deployed on [experimental.knooppuntnet.be](https://experimental.knooppuntnet.be).

**Closed by vmarc** 2021-07-22 16:54 UTC

**Comment by pyrog** [comment] 2022-11-05 12:09
Duplicate of #2 ?

PS: how this route could be **deactivated**?
