### ISSUE TITLE
Some background tiles stop loading after zoom 15

### ISSUE THREAD

**Issue by danieldegroot2** [vmarc/knooppuntnet#329] opened 2023-10-11 12:47 UTC
### **URL**
https://knooppuntnet.nl/nl/map/cycling?position=51.97678450,5.92965776,14

### **Observed behaviour**
1. Look at zoom 14 or below: looks okay
2. Zoom halfway into zoom 15 or above: some background tiles stop loading (here: right side of the screen)
3. No errors are returned in the browser's development console for this issue.

### **Expected behaviour**
All background tiles load successfully until max zoom (zoom 20), regardless of [manual tile regeneration](https://github.com/vmarc/knooppuntnet/issues/246#issuecomment-1192762066).

### **Screenshots**
**Zoom 14 or below** all background tiles seem to load fine
![image](https://github.com/vmarc/knooppuntnet/assets/67521919/183acc94-abba-4ea2-8d72-7ab48a4f347d)

**Halfway down zoom 15 or above** some background tiles stop loading (right side of the screen).
![image](https://github.com/vmarc/knooppuntnet/assets/67521919/099e5ec9-e1f7-47ab-a53d-6b97c15a6ef0)

**Comment by vmarc** [comment] 2023-10-11 13:06
@danieldegroot2 thanks for reporting this issue. I can reproduce this behavior on my laptop: that is a good first step in finding out what is going wrong here...

**Comment by vmarc** [comment] 2023-10-11 13:41
Interesting observation: the latest version of knooppuntnet in my development environment (version not released to the public yet) does not suffer from the same problem:

> ![planner](https://github.com/vmarc/knooppuntnet/assets/6596480/62ebf626-9396-416e-9139-6234a3bfd8d2)

This means that the necessary background tiles are available. In fact, I see these tiles loaded when looking in the browser development tools network tab.  So: no problem in the tile generation.

Knooppuntnet in development has OpenLayers v8.1.0, while production has OpenLayers v7.5.2.  Also, development uses MapboxVectorLayer from [ol-mapbox-style](https://github.com/openlayers/ol-mapbox-style) (v12.0.0), whereas production still uses MapLibreMap from [maplibre-gl](https://github.com/mapbox/mapbox-gl-js) (v1.15.2).

For now, I am going to assume that the problem is resolved in the new release of knooppuntnet.  I will leave this issue open until the new version is released on knooppuntnet.nl and knooppuntnet.be.

**Comment by danieldegroot2** [comment] 2023-10-20 11:50
I assume also the background layers on the Changeset pages will come back, unless it is intended these do not have one.

Ex. https://knooppuntnet.nl/nl/analysis/changeset/142858277/5798216
![image](https://github.com/vmarc/knooppuntnet/assets/67521919/5dbc6435-bf4b-4d11-97fe-1431190f9837)

**Comment by vmarc** [comment] 2023-11-02 12:37
Resolved (including background layers on the changeset pages) in release v4.1.0.

**Closed as completed by vmarc** 2023-11-02 12:37 UTC
Labels: bug
