### ISSUE TITLE
Accessibility of canoe and motorboat routes seems still wrong

### ISSUE THREAD

**Issue by A67-A67** [vmarc/knooppuntnet#28] opened 2018-09-17 15:27 UTC
Thanks for adding the accessibility analysis of canoe and motorboat routes in 2.0.10. However, still all routes are seen as inaccessible:
- [https://knooppuntnet.nl/nl/RouteUnaccessible/nl/rpn](https://knooppuntnet.nl/nl/RouteUnaccessible/nl/rpn)
- [https://knooppuntnet.nl/nl/RouteUnaccessible/nl/rmn](https://knooppuntnet.nl/nl/RouteUnaccessible/nl/rmn)

The [source code](https://github.com/vmarc/knooppuntnet/blob/develop/production/core/src/main/scala/kpn/core/engine/analysis/route/analyzers/AccessibilityAnalyzerImpl.scala) looks good, so it is quite strange.

**Comment by vmarc** [comment] 2018-09-18 13:50
@A67-A67 Thanks for reporting this bug. The problem is fixed in v2.0.11.

**Closed** 2018-10-24 18:52 UTC
Labels: bug
