### ISSUE TITLE
Change by country not up to date

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#219] opened 2021-11-01 14:57 UTC
The last changeset in [Home > Analysis > Hiking > France > Changes](https://knooppuntnet.nl/en/analysis/hiking/fr/changes) was at 2021-09-05 10:40.

For example, last changeset in [Home > Analysis > Network > Val d'Amour](https://knooppuntnet.nl/en/analysis/network/13328611/changes) (France) was at 2021-10-29 18:15.

**Comment by vmarc** [comment] 2021-11-01 16:26
@pyrog thanks for reporting this problem

Initial investigation shows that this problem may be caused by a mismatch between the structure of the documents in the analysis database and the definition of one of the database indexes (the latest changes to the database index code has somehow not been applied to this database).

At this moment the index is rebuilding.  This will take several hours to complete. During this time the information in the changes pages will be incomplete.

**Comment by pyrog** [comment] 2021-11-01 16:28
I just see the history starting from… 2013 😅 
Thank you Marc 😄

**Comment by vmarc** [comment] 2021-11-01 22:31
Index rebuild is complete. Looking forward to knooppuntnet v4.0 where these long index building will no longer exist.

**Closed as completed by vmarc** 2021-11-01 22:31 UTC
