### ISSUE TITLE
Geometries of intermunicipality aren't rendered

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#263] opened 2022-08-14 10:05 UTC
For example, [Pays de Gex agglo](https://knooppuntnet.nl/fr/analysis/hiking/fr/France:Ain:Pays%20de%20Gex%20agglo/map) is missing on the map, but lower level [Mijoux](https://knooppuntnet.nl/fr/analysis/hiking/fr/France:Ain:Pays%20de%20Gex%20agglo:Mijoux/map) or upper level [Ain](https://knooppuntnet.nl/fr/analysis/hiking/fr/France:Ain/map) are rendered.

Related to #225.

**Comment by vmarc** [comment] 2022-08-14 19:19
@pyrog thanks for reporting this problem

The problem is in the geojson that describes the  boundary of this location. The geojson for this location contains a GeometryCollection as top level geometry type, whereas the lower level locations contain a single Polygon at the top level.

I still have to further investigate why OpenLayers does not display the GeometryCollection, and whether there are any other locations that have a geojson that OpenLayers does not display.

As a temporary quick fix, I have moved the Polygon in the GeometryCollection to the top level if there is a single Polygon in the GeometryCollection. 

This way the location bounderies are displayed:

![issue](https://user-images.githubusercontent.com/6596480/184551593-f7f698b3-9406-4beb-bc95-03905505761b.png)

**Comment by vmarc** [comment] 2022-08-14 19:20
@pyrog thanks for reporting this problem

The problem is in the geojson that describes the  boundary of this location. The geojson for this location contains a GeometryCollection as top level geometry type, whereas the lower level locations contain a single Polygon at the top level.

I still have to further investigate why OpenLayers does not display the GeometryCollection, and whether there are any other locations that have a geojson that OpenLayers does not display.

As a temporary quick fix, I have moved the Polygon in the GeometryCollection to the top level if there is a single Polygon in the GeometryCollection. 

This way the location bounderies are displayed:

![issue](https://user-images.githubusercontent.com/6596480/184551738-feec34b0-0ba8-400c-9a19-ec797c2e832f.png)

**Comment by vmarc** [comment] 2022-08-15 18:06
Further investigation learns that OpenLayer does support displaying the GeometryCollection type in geojson.

The problem is that many of the location geojsons contain "EPSG:0" as coordinate reference system (1231 locations), which results in OpenLayers not displaying the bounderies for these locations.

The code has been changed to change "EPSG:0" to "EPSG:4326" for these locations.

The previous temporary quick fix has been taken out again.

**Closed as completed by vmarc** 2022-08-15 18:06 UTC
Labels: bug
