### ISSUE TITLE
Some pages don't have the favicon.ico

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#412] opened 2024-04-22 10:09 UTC
Tested on Safari. The icon seem sometime missing, sometime displayed 🤔 

<img width="33%" alt="History screen capture" src="https://github.com/vmarc/knooppuntnet/assets/2158081/8b1218fd-778a-44a1-a51a-8d9b7f714a2e">

https://knooppuntnet.nl/en/analysis/node/923938019
https://knooppuntnet.nl/en/analysis/node/923938019/map

https://knooppuntnet.nl/en/analysis/route/17500986
https://knooppuntnet.nl/en/analysis/route/17499598/map
https://knooppuntnet.nl/en/analysis/route/16145785/changes

https://knooppuntnet.nl/en/analysis/network/12409335/changes
https://knooppuntnet.nl/en/analysis/network/12409335/nodes
https://knooppuntnet.nl/en/analysis/network/12409335/routes

https://knooppuntnet.nl/en/analysis/hiking/fr/France:Drôme:Communauté%20de%20communes%20du%20Royans-Vercors:Bouvante/map

**Comment by vmarc** [comment] 2024-04-22 11:31
Looks ok on my laptop:

![image](https://github.com/vmarc/knooppuntnet/assets/6596480/4858172a-f1ed-4a68-a3c7-fbfccea8b44e)

**Comment by vmarc** [comment] 2024-06-03 14:36
I cannot reproduce this (tested on Safari).  I will close this issue for now, as I do not expect to be able to make any further progress with this.

**Closed as completed by vmarc** 2024-06-03 14:36 UTC
