### ISSUE TITLE
Make map behaviour consistent

### ISSUE THREAD

**Issue by Polfo** [vmarc/knooppuntnet#38] opened 2018-12-01 16:48 UTC
This issue repeats #12

I identified 3 map types:

First map type 
- has clickable routes and nodes
![image](https://user-images.githubusercontent.com/10303392/49330343-61837880-f58d-11e8-875a-e22f9be5c749.png)
e.g. https://www.knooppuntnet.be/en/map/rwn

The second map type 
- has layer selector in the top right corner
- does not have clickable objects
- shows markers for 1 node when node
- shows markers for start and end node and forward/backward routes when route
![image](https://user-images.githubusercontent.com/10303392/49330288-bc68a000-f58c-11e8-9000-97fa350f6b5e.png)
![image](https://user-images.githubusercontent.com/10303392/49330592-1b301880-f591-11e8-8da3-3bf62be76da5.png)
It can be reached by clicking on _map_ in a url like https://www.knooppuntnet.be/en/node/1333387947

The third map type
- does not have clickable objects
- does not have a layer selector in the top right corner
- shows pointers with nodes belonging to a network
![image](https://user-images.githubusercontent.com/10303392/49330447-0f435700-f58f-11e8-8ec0-cb50627e2a86.png)
e.g. https://www.knooppuntnet.be/en/network-map/1729060

Opinion: The different map types are a bit confusing, some are missing functionality.

Request: Could the nodes and routes be made clickable on the second and third map style?

Request: Could a layer selector be made available in the third type?

**Comment by vmarc** [comment] 2018-12-02 08:16
@Polfo thanks for this nice writeup of this issue.

Here are a few additions:

In the _"third map type"_ (the one that is associated to a specific network), the routes and nodes of all other networks are displayed in a grey when zoomed in sufficiently.

For the _"second map type"_ (map for specific node or specific route), the area to which you can zoom out is limited. This was intended to help the user in staying focused on the specific node or route. But I found that sometimes this actually hinders locating the node or route in a broader context. For example: _Where in the country is this node?_

There are 2 additional map types that illustrate node and route geometry changes in the _"changes"_ section of the node and route pages, and in the changeset pages ([example1](https://www.knooppuntnet.be/en/changeset/65060360/3258273), [example2](https://www.knooppuntnet.be/en/changeset/65058227/3258162)). Note that the changes information is only visible to OpenStreetMap users, after login through OpenStreetMap.

![route](https://user-images.githubusercontent.com/6596480/49337326-10699800-f612-11e8-9e27-e870aba84e07.png)

The route map uses different colors to highlight unchanged, added, updated and deleted ways. This map type comes with its own layers.

**Comment by vmarc** [comment] 2020-10-18 08:07
Fixed in release v3.0.0

**Closed by vmarc** 2020-10-18 08:07 UTC
Labels: enhancement
