### ISSUE TITLE
Improve monitor route analysis

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#351] opened 2023-11-17 13:47 UTC
In [Du Chemin Vendéen à la Voie de Tours](https://knooppuntnet.nl/fr/monitor/groups/fr-iwn-Camino/routes/Vend%C3%A9e-Tours), an Y shaped route, KPN display a continuous route.

<img width="80%" alt="KPN " src="https://github.com/vmarc/knooppuntnet/assets/2158081/8a2dede2-b626-405a-8ce3-7b66bdaa7053"> <img width="80%" alt="JOSM" src="https://github.com/vmarc/knooppuntnet/assets/2158081/d6003455-e5ac-4736-a732-c0cb71d6cd52">

<img width="80%" alt="WMT" src="https://github.com/vmarc/knooppuntnet/assets/2158081/a489a5aa-5e4a-408b-938c-ad220b6619b1">

**Comment by vmarc** [comment] 2023-11-17 18:53
Duplicate of #349 I think.

**Comment by vmarc** [comment] 2024-02-22 09:02
After the change of analysis algorithm in v4.3.1, this relation is reported nicely in knooppuntnet as having 2 segments (some gaps had to be filled first).  The relation has been changed in OSM in the mean while.  It now contains way members only, and does not contain subrelations anymore.  It still has type=superroute, so that is something that may still have to be changed in OSM (introduce subrelations again to mark segment as "aternative")?

> ![image](https://github.com/vmarc/knooppuntnet/assets/6596480/37976108-8938-4f1d-8766-f6503595f6b4)

**Closed as completed by vmarc** 2024-02-22 09:02 UTC
Labels: 1-monitor
