### ISSUE TITLE
Actual and Expected are mixed on IntegrityCheckFailed

### ISSUE THREAD

**Issue by NicolasGrosjean** [vmarc/knooppuntnet#262] opened 2022-07-31 16:25 UTC
You can see the issue in [this network](https://knooppuntnet.nl/en/analysis/network/13436769/facts) and clicking on row to see that the number in the Actual cell is the value of the _expected_lwn_route_relations_ tag.

**Comment by vmarc** [comment] 2022-07-31 20:19
Thanks for reporting this issue.

The problem is in [NetworkInfoFactAnalyzer.scala](https://github.com/vmarc/knooppuntnet/blob/develop/server/src/main/scala/kpn/server/analyzer/engine/analysis/network/info/analyzers/NetworkInfoFactAnalyzer.scala) at line 98 and 99. The 'Actual' and 'Expected' arguments are in the wrong order.

**Comment by vmarc** [comment] 2022-08-01 17:43
Fixed in code, and regenerated data in database.

---

Before:

![before](https://user-images.githubusercontent.com/6596480/182209867-3bc9a901-e8f4-4544-83bc-4aac0c8e2fc3.png)


---

After:

![after](https://user-images.githubusercontent.com/6596480/182209859-07c9d1ba-e140-410d-b54c-569373273617.png)

**Closed as completed by vmarc** 2022-08-01 17:43 UTC
Labels: bug
