### ISSUE TITLE
Can't update the reference in monitor

### ISSUE THREAD

**Issue by pyrog** [vmarc/knooppuntnet#363] opened 2023-12-04 13:56 UTC
[fr-nwn/GR 75](https://knooppuntnet.nl/fr/monitor/admin/groups/fr-nwn/routes/GR%2075) had initially a GPX file as reference.

I use the relation itself as reference to refresh the monitor data, but it seem that KPN keep the GPX filename.
Note: a refresh monitor feature/button is missing (at least for administrators ?)

I try to update the monitor with the same GPX reference:
- select GPX as reference
- download GPX file

KPN display `None.get`

<img width="33%" alt="Screencopy" src="https://github.com/vmarc/knooppuntnet/assets/2158081/aabf9b9c-e704-4669-9c17-153b13cb78b1">

KPN display `GPX: "GR 75.gpx" ` but the reference used is still the relation itself.

<img width="33%" alt="Details" src="https://github.com/vmarc/knooppuntnet/assets/2158081/1b28ce29-19dc-49d9-8cbf-a3a4fcdc6900">

**Comment by vmarc** [comment] 2023-12-16 09:25
I could not reproduce this issue.  I suppose the problem may have been resolved by the fix for #360.  Perhaps the problem was seen with an old version of knooppuntnet. Please re-open if this is still an issue.

**Closed as completed by vmarc** 2023-12-16 09:25 UTC
Labels: 1-monitor
